# Generated by Django 4.0 on 2022-01-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
