# Generated by Django 4.0 on 2022-01-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_i_cat_item_i_categ'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
