# Generated by Django 4.0 on 2022-01-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('i_categ', models.CharField(max_length=30)),
                ('i_name', models.CharField(max_length=30)),
                ('i_desc', models.CharField(max_length=30)),
                ('i_price', models.CharField(max_length=30)),
                ('i_offerprice', models.CharField(max_length=30)),
                ('i_pic', models.ImageField(default='', upload_to='img/%y')),
            ],
        ),
    ]
