# Generated by Django 4.0.1 on 2022-01-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
